apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  namespace: demo
  labels:
    name: demo
data:
  application.properties: |-
    spring.application.name=demo
    spring.application.version=1.0-SNAPSHOT
    #spring.profiles.active=local
    logging.level.com.mycompany=debug
    management.endpoints.web.exposure.include=*
    management.metrics.distribution.percentiles-histogram.http.server.requests=true
    #management.metrics.distribution.sla.http.server.requests=50ms
    logstash.host=localhost